# Generated by Django 4.2.26 on 2025-12-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_systeminfo_allow_action_sections_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systeminfo",
            name="allow_showing_description",
            field=models.BooleanField(default=True),
        ),
    ]
