# Generated by Django 4.2.26 on 2025-12-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0017_action_section_historicalaction_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="description",
            field=models.TextField(blank=True, max_length=175),
        ),
        migrations.AlterField(
            model_name="historicalaction",
            name="description",
            field=models.TextField(blank=True, max_length=175),
        ),
    ]
