# Generated by Django 4.2.26 on 2025-12-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_userpreferences_custom_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="allow_showing_description",
            field=models.BooleanField(default=True),
        ),
    ]
